/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grasmaaier;

import grasmaaier.basics.Parameters;
import grasmaaier.com.MyListener.TalkBack;
import grasmaaier.com.NewComunicator;
import grasmaaier.com.checkComponents;
import java.awt.Window;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.util.Timer;

/**
 *
 * @author hylkema
 */
public class Pilot extends javax.swing.JFrame implements TalkBack {

  private static final String sep = ":";
//  private final PilotServer pilotServer;
  private static NewComunicator myCom;
  private static Timer timer;

  /**
   * Creates new form pilot
   */
  public Pilot() {
    initComponents();
    Pilot.mapViewer.selectTile(Parameters.lat, Parameters.lon);
//    this.pilotServer  = new PilotServer();
    Pilot.myCom = new NewComunicator();
    Window[] mainframe = java.awt.Window.getWindows();
    mainframe[0].setIconImage(new ImageIcon("./Icons/grasmaaier.png").getImage());
    timer = new Timer();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane2 = new javax.swing.JTabbedPane();
    mainPanel = new javax.swing.JPanel();
    startButton = new javax.swing.JButton();
    Stop = new javax.swing.JButton();
    mapViewer = new grasmaaier.basics.mapViewer();
    gpsLed = new grasmaaier.basics.Led();
    bladeMotorLed = new grasmaaier.basics.Led();
    motorLed = new grasmaaier.basics.Led();
    batteryLed = new grasmaaier.basics.Led();
    jButton3 = new javax.swing.JButton();
    msgField = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    directionLed = new grasmaaier.basics.Led();
    gpsBaseLed = new grasmaaier.basics.Led();
    iconLabel = new javax.swing.JLabel();
    Blades = new javax.swing.JPanel();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    Motor = new javax.swing.JPanel();
    motorSpeed = new javax.swing.JSlider();
    jLabel1 = new javax.swing.JLabel();
    motorSpeedLabel = new javax.swing.JLabel();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    GPS = new javax.swing.JPanel();
    Battery = new javax.swing.JPanel();
    Direction = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    dirSpeed = new javax.swing.JSlider();
    jLabel3 = new javax.swing.JLabel();
    dirSteps = new javax.swing.JTextField();
    jButton8 = new javax.swing.JButton();
    GPSBase = new javax.swing.JPanel();
    updateButton = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    lonField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    latField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    altField = new javax.swing.JTextField();
    lonDifField = new javax.swing.JTextField();
    latDifField = new javax.swing.JTextField();
    altDifField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    lonStdevField = new javax.swing.JTextField();
    latStdevField = new javax.swing.JTextField();
    altStdevField = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    samplePeriodField = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Joukes grasmaaier");

    startButton.setText("Start");
    startButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startButtonActionPerformed(evt);
      }
    });

    Stop.setText("Stop");
    Stop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StopActionPerformed(evt);
      }
    });

    gpsLed.title("GPS");
    gpsLed.red();

    bladeMotorLed.title("Blades");
    bladeMotorLed.red();

    motorLed.title("Motor");
    motorLed.red();

    batteryLed.title("Batterie");
    batteryLed.red();

    jButton3.setText("Test");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton2.setText("shutdown");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    directionLed.title("Direction");
    directionLed.red();

    gpsBaseLed.title("GPS base");
    gpsBaseLed.red();

    iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grasmaaier.png"))); // NOI18N

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(mapViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addComponent(startButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Stop)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(gpsBaseLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(gpsLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(bladeMotorLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(motorLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(batteryLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(directionLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(iconLabel, javax.swing.GroupLayout.Alignment.LEADING))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    mainPanelLayout.setVerticalGroup(
      mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(mapViewer, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(mainPanelLayout.createSequentialGroup()
            .addComponent(gpsLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bladeMotorLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(motorLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(batteryLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(directionLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(64, 64, 64)
            .addComponent(iconLabel)
            .addGap(18, 18, 18)
            .addComponent(gpsBaseLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(9, 9, 9)
        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(startButton)
          .addComponent(Stop)
          .addComponent(jButton3)
          .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("Main", mainPanel);

    jButton4.setBackground(new java.awt.Color(255, 51, 51));
    jButton4.setText("Stop");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jButton5.setBackground(new java.awt.Color(0, 204, 0));
    jButton5.setText("Start");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout BladesLayout = new javax.swing.GroupLayout(Blades);
    Blades.setLayout(BladesLayout);
    BladesLayout.setHorizontalGroup(
      BladesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(BladesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton5)
        .addContainerGap(867, Short.MAX_VALUE))
    );
    BladesLayout.setVerticalGroup(
      BladesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(BladesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(BladesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton4)
          .addComponent(jButton5))
        .addContainerGap(281, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("Blades", Blades);

    Motor.setPreferredSize(new java.awt.Dimension(200, 79));

    motorSpeed.setMinimum(-100);
    motorSpeed.setPaintLabels(true);
    motorSpeed.setPaintTicks(true);
    motorSpeed.setValue(0);
    motorSpeed.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        motorSpeedMouseReleased(evt);
      }
    });
    motorSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        motorSpeedStateChanged(evt);
      }
    });

    jLabel1.setText("Speed");

    motorSpeedLabel.setText("0");

    jButton6.setBackground(new java.awt.Color(255, 0, 51));
    jButton6.setText("Stop");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });

    jButton7.setBackground(new java.awt.Color(51, 204, 0));
    jButton7.setText("Start");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton7ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout MotorLayout = new javax.swing.GroupLayout(Motor);
    Motor.setLayout(MotorLayout);
    MotorLayout.setHorizontalGroup(
      MotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MotorLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(MotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jButton6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(motorSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(motorSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        .addContainerGap())
    );
    MotorLayout.setVerticalGroup(
      MotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MotorLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(MotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(motorSpeedLabel)
          .addComponent(motorSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(MotorLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(MotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButton6)
              .addComponent(jButton7))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("Motor", Motor);

    javax.swing.GroupLayout GPSLayout = new javax.swing.GroupLayout(GPS);
    GPS.setLayout(GPSLayout);
    GPSLayout.setHorizontalGroup(
      GPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1026, Short.MAX_VALUE)
    );
    GPSLayout.setVerticalGroup(
      GPSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 318, Short.MAX_VALUE)
    );

    jTabbedPane2.addTab("GPS", GPS);

    javax.swing.GroupLayout BatteryLayout = new javax.swing.GroupLayout(Battery);
    Battery.setLayout(BatteryLayout);
    BatteryLayout.setHorizontalGroup(
      BatteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1026, Short.MAX_VALUE)
    );
    BatteryLayout.setVerticalGroup(
      BatteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 318, Short.MAX_VALUE)
    );

    jTabbedPane2.addTab("Battery", Battery);

    jLabel2.setText("Speed");

    dirSpeed.setMajorTickSpacing(10);
    dirSpeed.setMinimum(-100);
    dirSpeed.setPaintLabels(true);
    dirSpeed.setPaintTicks(true);
    dirSpeed.setValue(0);
    dirSpeed.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        dirSpeedMouseReleased(evt);
      }
    });
    dirSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        dirSpeedStateChanged(evt);
      }
    });

    jLabel3.setText("Steps");

    jButton8.setText("Go");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton8ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout DirectionLayout = new javax.swing.GroupLayout(Direction);
    Direction.setLayout(DirectionLayout);
    DirectionLayout.setHorizontalGroup(
      DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(DirectionLayout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addGroup(DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(DirectionLayout.createSequentialGroup()
            .addComponent(jButton8)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(DirectionLayout.createSequentialGroup()
            .addGroup(DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(DirectionLayout.createSequentialGroup()
                .addComponent(dirSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
              .addGroup(DirectionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(dirSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
    );
    DirectionLayout.setVerticalGroup(
      DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(DirectionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(dirSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(12, 12, 12)
        .addGroup(DirectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(dirSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton8)
        .addContainerGap(202, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("Direction", Direction);

    updateButton.setText("Update");
    updateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateButtonActionPerformed(evt);
      }
    });

    jLabel4.setText("lon :");

    jLabel5.setText("lat :");

    jLabel6.setText("alt :");

    jLabel7.setText("error");

    jLabel8.setText("error");

    jLabel9.setText("error");

    jLabel10.setText("m std dev");

    jLabel11.setText("m std dev");

    jLabel12.setText("m std dev");

    jLabel13.setText("sample period");

    jLabel14.setText("hours");

    javax.swing.GroupLayout GPSBaseLayout = new javax.swing.GroupLayout(GPSBase);
    GPSBase.setLayout(GPSBaseLayout);
    GPSBaseLayout.setHorizontalGroup(
      GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(GPSBaseLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(updateButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(GPSBaseLayout.createSequentialGroup()
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(samplePeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel14))
          .addGroup(GPSBaseLayout.createSequentialGroup()
            .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addComponent(jLabel5)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(latField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(lonField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7))
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(altField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(lonDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lonStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(latDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(latStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(GPSBaseLayout.createSequentialGroup()
                .addComponent(altDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(107, Short.MAX_VALUE))
    );

    GPSBaseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {altDifField, altField, latDifField, latField, lonDifField, lonField});

    GPSBaseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {altStdevField, latStdevField, lonStdevField});

    GPSBaseLayout.setVerticalGroup(
      GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(GPSBaseLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(updateButton)
          .addComponent(jLabel4)
          .addComponent(lonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lonDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(jLabel10)
          .addComponent(lonStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(latField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(latDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8)
          .addComponent(jLabel11)
          .addComponent(latStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(altField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(altDifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9)
          .addComponent(jLabel12)
          .addComponent(altStdevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(GPSBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(samplePeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel14))
        .addContainerGap(200, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("GPS Base", GPSBase);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane2.getAccessibleContext().setAccessibleName("Blades");
    jTabbedPane2.getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    try {
      //    pilotServer.start();
      System.out.println("start button");
      Pilot.myCom.start();
      Thread.sleep(2000);
      Pilot.myCom.addListener(this);
      timer.schedule(new checkComponents(Pilot.myCom), 0, 5000);
    } catch (InterruptedException ex) {
      Logger.getLogger(Pilot.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_startButtonActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Pilot.myCom.send(Pilot.msgField.getText());
  }//GEN-LAST:event_jButton3ActionPerformed

  private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
//    this.pilotServer.send("Blades:Stop");
  }//GEN-LAST:event_StopActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Pilot.myCom.send("Grasmaaier:Global:Quit");
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Pilot.myCom.send("Grasmaaier:Motor:Stop");
  }//GEN-LAST:event_jButton6ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    Pilot.myCom.send("Grasmaaier:Motor:Start");
  }//GEN-LAST:event_jButton7ActionPerformed

  private void motorSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_motorSpeedStateChanged

  }//GEN-LAST:event_motorSpeedStateChanged

  private void motorSpeedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motorSpeedMouseReleased
    int value = motorSpeed.getValue();
    Pilot.myCom.send("Grasmaaier:Motor:SetSpeed:" + value);
    motorSpeedLabel.setText(String.valueOf(value));
  }//GEN-LAST:event_motorSpeedMouseReleased

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Pilot.myCom.send("Grasmaaier:Blades:Stop");
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    Pilot.myCom.send("Grasmaaier:Blades:Start");
  }//GEN-LAST:event_jButton5ActionPerformed

  private void dirSpeedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dirSpeedMouseReleased
    // TODO add your handling code here:
  }//GEN-LAST:event_dirSpeedMouseReleased

  private void dirSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dirSpeedStateChanged
    // TODO add your handling code here:
  }//GEN-LAST:event_dirSpeedStateChanged

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    Pilot.myCom.send("Grasmaaier:Direction:Steps:" + dirSteps.getText() + ":" + dirSpeed.getValue());

  }//GEN-LAST:event_jButton8ActionPerformed

  private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    Pilot.myCom.send("GpsBase:Update");
  }//GEN-LAST:event_updateButtonActionPerformed
  public static void moveMaaier(double lat, double lon) {
    Pilot.mapViewer.moveMaaier(lat, lon);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Pilot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new Pilot().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Battery;
  private javax.swing.JPanel Blades;
  private javax.swing.JPanel Direction;
  private javax.swing.JPanel GPS;
  private javax.swing.JPanel GPSBase;
  private javax.swing.JPanel Motor;
  private javax.swing.JButton Stop;
  private javax.swing.JTextField altDifField;
  private javax.swing.JTextField altField;
  private javax.swing.JTextField altStdevField;
  public static grasmaaier.basics.Led batteryLed;
  public static grasmaaier.basics.Led bladeMotorLed;
  private javax.swing.JSlider dirSpeed;
  private javax.swing.JTextField dirSteps;
  public static grasmaaier.basics.Led directionLed;
  public static grasmaaier.basics.Led gpsBaseLed;
  public static grasmaaier.basics.Led gpsLed;
  private javax.swing.JLabel iconLabel;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTabbedPane jTabbedPane2;
  private javax.swing.JTextField latDifField;
  private javax.swing.JTextField latField;
  private javax.swing.JTextField latStdevField;
  private javax.swing.JTextField lonDifField;
  private javax.swing.JTextField lonField;
  private javax.swing.JTextField lonStdevField;
  private javax.swing.JPanel mainPanel;
  private static grasmaaier.basics.mapViewer mapViewer;
  public static grasmaaier.basics.Led motorLed;
  private javax.swing.JSlider motorSpeed;
  private javax.swing.JLabel motorSpeedLabel;
  public static javax.swing.JTextField msgField;
  private javax.swing.JTextField samplePeriodField;
  private javax.swing.JButton startButton;
  private javax.swing.JButton updateButton;
  // End of variables declaration//GEN-END:variables

  @Override
  public void parse(String msg) {
    String[] tokens = msg.split(":");
    System.out.println("token 0 = mov" + tokens[0]);
    switch (tokens[0]) {
      case "Motor":
        this.parseMotor(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
      case "Blades":
        this.parseBlades(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
      case "Battery":
        this.parseBattery(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
      case "GPS":
        this.parseGPS(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
      case "Direction":
        this.parseDirection(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
      case "GpsBase":
        this.parseGpsBase(Arrays.copyOfRange(tokens, 1, tokens.length));
        break;
    }
  }

  private void parseDirection(String[] msg) {
    if (msg[0].equals("Online")) {
      Pilot.directionLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.directionLed.red();
    }
  }

  private void parseBlades(String[] msg) {
    if (msg[0].equals("Online")) {
      Pilot.bladeMotorLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.bladeMotorLed.red();
    }
  }

  private void parseMotor(String[] msg) {
    if (msg[0].equals("Online")) {
      Pilot.motorLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.motorLed.red();
    }
  }

  private void parseBattery(String[] msg) {
    if (msg[0].equals("Online")) {
      Pilot.batteryLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.batteryLed.red();
    }
  }

  private void parseGPS(String[] msg) {
    if (msg[0].equals("Online")) {
      Pilot.gpsLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.gpsLed.red();
    }
  }

  private void parseGpsBase(String[] msg) {
    if (msg[0].equals("Online") || msg[0].equals("Alive")) {
      Pilot.gpsBaseLed.green();
    }
    if (msg[0].equals("Offline")) {
      Pilot.gpsBaseLed.red();
    }
    if (msg[0].equals("Update")) {
      this.updateGpsBase(msg);
    }
  }

  private Double Distance(double deg) {
    Double R = 6371000.0; // metres
    return R * Math.toRadians(Math.abs(deg));
  }

  private void updateGpsBase(String[] msg) {
    
    DecimalFormat decim1 = new DecimalFormat("0.00");
    DecimalFormat decim2 = new DecimalFormat("0.000000");
    
    latField.setText(msg[2]);
    double latMin = Double.parseDouble(msg[3]);
    double latMax = Double.parseDouble(msg[4]);
    double latStd = Double.parseDouble(msg[5]);
    latDifField.setText(decim2.format(this.Distance(0.5*(latMax - latMin))));
    latStdevField.setText(decim2.format(this.Distance(latStd)));

    lonField.setText(msg[7]);
    double lonMin = Double.parseDouble(msg[8]);
    double lonMax = Double.parseDouble(msg[9]);
    double lonStd = Double.parseDouble(msg[10]);
    lonDifField.setText(decim2.format(this.Distance(0.5*(lonMax - lonMin))));
    lonStdevField.setText(decim2.format(this.Distance(lonStd)));

    altField.setText(msg[12]);
    double altMin = Double.parseDouble(msg[13]);
    double altMax = Double.parseDouble(msg[14]);
    double altStd = Double.parseDouble(msg[15]);
    altDifField.setText(decim2.format(altMax - altMin));
    altStdevField.setText(decim2.format(Math.sqrt(altStd)));

    double period = Double.parseDouble(msg[16]) / 3600.0;
    samplePeriodField.setText(decim1.format(period));

    Pilot.mapViewer.moveBase(Double.parseDouble(latField.getText()), Double.parseDouble(lonField.getText()));
  }
}
